---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 31306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-mysql
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /data
            - name: mysql-initdb # ponto de montagem para volume docker entrypoint para que possa aplicar o script sql on the fly ao subir o container docker
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
---
apiVersion: v1
kind: ConfigMap # config map para aplicar o script sql on the fly
metadata:
  name: mysql-initdb-config
data:
  database_schema.sql: | 
    CREATE DATABASE packages;
    USE packages;
    CREATE TABLE offer ( Id int(11) NOT NULL AUTO_INCREMENT,Text varchar(255) NOT NULL,CreateDate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (Id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
