version: "3.3"

services: 

  dbdelta:
    env_file:
      - env.list
    image: vitorta/dbdelta
    container_name: dbdelta
    volumes:
      - voldbdelta:/var/lib/mysql
    networks:
      - delta   

  nodedelta:
    env_file:
      - env.list
    image: vitorta/nodedelta
    container_name: nodedelta
    depends_on: 
      - dbdelta
    networks:
      - delta
     
  nginxdelta:
    image: vitorta/nginxdelta
    container_name: nginxdelta
    ports:
      - "80:80"
    depends_on: 
      - nodedelta   
    networks:
      - delta      
volumes:
  voldbdelta:
networks:
  delta: