version: '3'

services:
  loadbalancer:
    build: ./src/loadbalancer/
    restart: unless-stopped
    networks:
     - public
    depends_on:
      - app

  app:
    build: ./src/app/
    restart: unless-stopped
    environment:
      MYSQL_HOST: "database"
      MYSQL_USER: "root"
      MYSQL_PASS: "QueroCafe"
    networks:
     - public
     - private
    depends_on:
      - database

  database:
    image: mysql:5
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "QueroCafe"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - "database_data:/var/lib/mysql"
    networks:
     - private

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
     - private

networks:
  public:
  private:

volumes:
  database_data:
