version: '3'

services:
    nodejs:
      build:
        context: .
        dockerfile: Dockerfile
      image: nodejs
      container_name: nodejs-server-hurb-test
      networks:
        - app-network
    webserver:
      image: nginx:latest
      container_name: nginx-server
      ports:
        - "80:80"
      volumes:
        - ./nginx:/etc/nginx/conf.d
      depends_on:
        - nodejs
      networks:
        - app-network
    mysql:
      image: mysql:5.7
      container_name: mysql-db
      ports:
        - 3306:3306
      volumes:
        - ./mysql:/docker-entrypoint-initdb.d/database_schema.sql
      environment:
        MYSQL_ROOT_PASSWORD: passwords
        MYSQL_DATABASE: packages
        MYSQL_USER: user_packages
        MYSQL_PASSWORD: passwords
      networks:
        - app-network
networks:
    app-network:
