version: "3.3"

services: 

  dbdelta:
    image: vitorta/dbdelta 
    volumes:
      - voldbdelta:/var/lib/mysql
    networks:
      - delta   

  nodedelta:
    image: vitorta/nodedelta
    depends_on: 
      - dbdelta
    networks:
      - delta
     
  nginxdelta:
    image: vitorta/nginxdelta 
    ports:
      - "80:80"
    depends_on: 
      - nodedelta   
    networks:
      - delta      
volumes:
  voldbdelta:
networks:
  delta: