version: '3'
services:
  db:
    image: mysql:5.7.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "QtxS9Vt4@3"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "QtxS9Vt4"
      MYSQL_DATABASE: "packages"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - "db_vol:/var/lib/mysql"
      - "./database:/docker-entrypoint-initdb.d"
    networks:
      - internal
  notes-api:
    build: ./src/
    restart: always
    environment:
      NODEJS_API_PORT: 8888
      MYSQL_HOST: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "QtxS9Vt4"
    networks:
      - internal
      - external
    depends_on:
      - db
  proxy:
    build: ./proxy/
    restart: always
    environment:
      NGINX_PORT: 80
      API_HOST: notes-api
      API_PORT: 8888
    ports:
      - 80:80
    networks:
      - external
    depends_on:
      - notes-api
networks:
  internal:
  external:
volumes:
  db_vol: