apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  mysql-root-password: 4oCcdXNlcnBhY2thZ2VzcGFzc3dvcmRz4oCd
  mysql-user: 4oCcdXNlcl9wYWNrYWdlc+KAnQ==
  mysql-password: 4oCccGFzc3dvcmRz4oCd
