version: '3'
services:
    proxy:
        image: ${PROXY_IMAGE_NAME}
        container_name: proxy
        ports:
            - 80:80
        depends_on:
            - app
    app:
        image: ${APP_IMAGE_NAME}
        container_name: app
        ports:
            - 80
        env_file:
            - ../.db.secrets
        environment:
            NODEJS_API_PORT: 80
            MYSQL_HOST: db
        depends_on:
            - db
    db:
        image: ${DB_IMAGE_NAME}
        container_name: db
        ports:
            - 3306
        env_file:
            - ../.db.secrets
