apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: delta-ingress
spec:
  rules:
  - host: minekube-dns
    http:
      paths:
      - path: /packages
        backend:
          serviceName: delta-node
          servicePort: 8888