apiVersion: v1
kind: Service
metadata:
  name: delta-database
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: database

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: database-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: delta-database
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      volumes:
      - name: database-storage
        persistentVolumeClaim:
          claimName: database-pvc
      containers:
      - name: delta-database
        image: "delta-database:latest"
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/
          name: database-storage
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root_password
        - name: MYSQL_DATABASE
          value: packages
        - name: MYSQL_USER
          value: user_packages
        - name: MYSQL_PASSWORD
          value: passwords
