apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: challenge-delta-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /packages
spec:
  rules:
  - host: challenge-delta.info
    http:
      paths:
      - path: /
        backend:
          serviceName: nodeapp
          servicePort: 8888