apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/app-root: /packages
spec:
  rules:
  - host: challenge-delta.info
    http:
      paths:
      - path: /
        backend:
          serviceName: nodeapp
          servicePort: 8888