apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: "nodeapp:latest"
        imagePullPolicy: Never
        ports:
        - containerPort: 8888
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: MYSQL_PASSWORD
        - name: MYSQL_URL
          value: db
        - name: NODEJS_API_PORT
          value: "8888"

---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp
spec:
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
  selector:
    app: nodeapp